packageName: generic
experiments:
  - name: pod-delete
    CSV: pod-delete.chartserviceversion.yaml
    desc: "pod-delete"
  - name: harness-pod-kill-failure
    CSV: harness-pod-kill-failure.chartserviceversion.yaml
    desc: "fake-workflow-failure-demo"
