apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: harness-pod-kill-failure
  version: 0.1.0
  annotations:
    categories: demo
spec:
  displayName: harness-pod-kill-failure
  categoryDescription: >
    chaos-demo
  keywords:
    - "pods"
    - "kubernetes"
    - "demo"
  platforms:
    - "Minikube"
  maturity: alpha
  maintainers:
    - name: ksatchit
      email: karthik@chaosnative.com
  minKubeVersion: 1.12.0
  provider:
    name: ChaosNative
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: latest
  links:
    - name: Documentation
      url: https://docs.litmuschaos.io/docs/getstarted/
  icon:
    - url:
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/chaosnative/harness-chaos-demo/main/charts/generic/charness-pod-kill-failure/experiment.yaml
